#!/bin/sh
# /etc/init.d/PiReC
### BEGIN INIT INFO
# Provides:          PiReC
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
screen -dmS PiReC sudo java -Dpi4j.linking=dynamic -jar /home/pi/artifacts/PiReC-0.1-SNAPSHOT-jar-with-dependencies.jar
